#!/bin/bash
#PBS -l nodes=1:ppn=8
#PBS -l walltime=00:05:00

# Copyright (c) 2021 brainlife.io at University of Texas at Austin and Indiana University
# 
# This is the main file run by the brainlife.io orchestration system
#
# Author: Giulia Berto

# Run main (HCP systems)
singularity exec -e docker://brainlife/mcr:2020a ./compiled/main
